// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
ff..ff...ffb.ff.f.......f.....f...ffff...ffff...f......f.f..f.....f.fffffffffbfffffff.fff..fff...ff..f..f.ff.ffff...f.......ff....f.f..........f........f.......
.f.ff...ffb..f.f........f...ff......fffffff..fffffffffffffffff..ffffff.......fb......ffffff...f...fff...f..f.fffff...f.......fffffffffffffffffffff......f.......
f.ff...f.b..f..f........f..f.......f.fff.ffff..ff.....f.fff...fff....ff......ffb.......fffffff.f...ff..f....f.ff..ff.f...ffff.f.f...ff..........f.ffff...f......
ffff...ffb.f...f........f..f......fff.f.ff..ff.ffffffffffffffffffffffffffffff.fb.....ff....ff.fff.ff.f.f....ff..f...fffff......f.ff.f.f..........f....ffff......
ff.f..f.b.ff..f........f..f......ff..fff....ffff...ffffff.ff.......ffffff..f.fffb...f........ff.ff..f.f.....fff..f.ffff.........f..f.f.f.........f.......fff....
f..f.f..bff...f........f.f.....ff.f.ff...ffff.f.ffff..ffffff.........fff.fff...fbfff...........ff.ff.f.f...ff.ff.ff..fffffff.....f..ff.f..........f........fff..
.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbfff
.bff...bff...f.........ff...ff...ff.ff......ffff....fff..ffff...........fff....ffb.....ff......f..fffffff.f.ffffff.ff.f...f..ffff..f...ff........fff.......fb...
.bff..bf.f...f........ff...f....ffff......fff.f.....ffff...ff...........ffffffffffbff....ff...f.....fbbb.f.fff.f..f..ff...f...f..ff.f..ff......ff..f........b...
.bf...b.f...f.........ff.ff....ffff.....ff..fff....fffffffffffffff...fff.f.ff..f.fbffffffffffff....bbf..bbbff...f.ff.ff....f..f..fffffffffffffffffffff......b...
.bf..bf.f...f.........f.f.....fff..f..ff...ff.f.fffff....ff.fff...fff....ff.fff..f.bff..ff...ffffbb.f.fffffbb...f.ff..f.....fffff...ff..fff..f......f.ffff..b...
fbf..b..f...f.........ff.....fff....ffffffff..ff.ff.f......fff.ffff..ff..ff..ff...fb..ff..ff.f.bbf.f..fff.fffbb.f.f.f.ff.ffffff.......f..f.ff.......f.....ffbf..
fbf..b.f....f..ffffffffffffff.f....f......f..ff.f.ff........ff..fffffffffffffffffffbffffffffbbbffffffffff.fffb...ffbbffff....ff.......ff.ff.f........f......bfff
.bf.bf.f...ffff.....fff....ffff..ff......f.ff.ff.f.ffffffffffffffffffff.ffffffffffffbff..fbbff....ffffffff.bb.f..bb.fff.f.....f........ff.f..f.......f......bf..
.b.fb.f...ff.......f.f.fffffffffff...ffffffffffffffffffffffffffffffffffff.fff..ffff.bfffbbffffffffffff..ffbfffbbb.ff..f..f....f........f.ff..f.......f.b....bf..
.b.fb.f..f.f......f.fff.f.f..fffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbfffff..f.ffffff..bfbbb..ffff..ff.f...f.f........ffff..f......bb.....bf..
.bfb..f.f.f......f.ffffffffffffffff..f.ff....ffffffffffffffffffffff...f.f.ffffff.f.bbb....ffff..ff.fffffbbbffbff.ff.f.f.f.f.f..f.......ff.ff...f...bbbf.....bf..
.bfb..ff..f.....fff.ffffff.fff....fff.ff..ffffffffff...ff.fffffffff....fffffff.ffbbf.bf...f..ff.ff.fffbbbffbbfff..f..fffffff...bb.....bbbfff....fbb.b.f.....bf..
.bfb.f....f...ffff.fff..fffff........fffff.ffffffffffff.fff..fffffff..fffffffffbbffffb.f..f....ff.ffbb.ffbbffff.f..f..f..f.fbbbbfbbbbbb..ffff..bb..b..f.....bf..
.b.b.f....f..ff.fff.ff.ff..f.........ffffffffffffffffffffffffffffffffffffff.bbbffffffbf.ff....f.fbbbbf.bbbf.ffff.fffffffbbbb.bbbb.bbb.f.fffffbbfffb....f....bf..
.bfbff...f.fffff...fffffffffffffffffffffffff.fffffffffffffffff.....fffffffbbff.f..fffbffff...ffbbffbfbbbbfffffffffff.bbbbbbbb..bbb....fffffbbf...bfff..f....bf..
fbfb.f...ff.fff...f.ffff.ff.......ffff.fffffffffff..ffff.f.f.ffff.ff.fffbb.ffffff..ffbffffffbbbf.bbbbfbff..ffffff.bbbbbbbbbffbbfffffffffffbfff..b.f..f.f....bf..
fbfbf....fffff....fff.f6f6f666666fff666fffffffffff6f6ffff6ff6f6ffff66bbbfff6f66ffffffbfffbbb6666bfbfbbf66666fffbbbb6bbbbbbbbbff..f...ff.bbff.ffbf..f..ff....bf..
fbfbf...ff.f.f..ff..f.ff.f......ffff..ffffffffff.ff..ff.f.f..f..fffbbf..ffffff.fff.ffbfbb.fff..bbbfbff....bbbbbffbbbfbbbbbffff...f..ffbb..ff.fb..ff.f.ff....bf..
.b.bf..f.ff..ffff...f.f6.f.....f..f.fff.ff.fffffff...ff.fff..f.ffbbffff.ff.ff.ffffffbbbfffffffbb.bbfffbbbbbfffbbbbbbbbbbff6.ffff.f..bb....f.fbf....ff..f....bf..
.b.bfff.ff..ffff....fff6.f...ff..fffff.fff.ffffffff..ffff.fffffbb..fff.ffff.ffffffbbfbffffffbbffbbbbbbbb....bbbbbbbbbfff.f6..ff.ffbbff....f.bf.f....ff.f....bf..
.b.bff..ff.fff.f....ffffffffffffffffffffffffffffffffffcffffcbbbfccffccfcfffffffbbbffcbcfffbbbbbbbfbbbfffcbbbbbbbbfccfcffffffffffbbfffff.bbbbff.f....ffff....b...
fbfbff..f.f.fbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbbb.fffbbbbbbbb.ffff.fffffff..fbb.bbbbbbbfff.ff.f....f.fff...b...
fb.bf..fff.ffb..fffffffffcff.f.fffff....fff.ff.fff...fffbbf.fffff.f...ffffbbbbbbffffbbbbbb.fbbbffffbbbbbbbbbf...fffff.f.f.bbbbbbbf..ffff..ffff..f...f.ff.f..b...
fb.bf..ff.f.fbff.f.fff.6ffff4fffff4f444f4ffff4444ff44bbbfff4ff4fff44ff4bbbbbbfb4bbbb4bbbbbbbffffbbbbbbbbbfffffffffbbbbbbbb6bb.f..f..ff..ff...ffffffff..f..ffb...
fb.bf.ffff..fb..f.ffff.ffcffffffff.f...f.ffffffffffbbfff.fffff.f.f.fbbbf.fffbbbbfffbbbbbbbff.bbbbbbfbbf.ff.bbbbbbbfff..fcbb.ffff.f..ff...ff..f.ff...ff.f..ffb...
fbfbffff.f..fb..ffffffffffffffff5ff5555ffffff5fffbbfffffffffffffffbbbfffbbbb.bff.bbbbbbbfbbbbbbbfbbbbbbbbbb.fffffff.ff.bbf6..fff.f..ff...f.fff..ff..f.fff..fb...
fbfbff.ff..ffbfff.f.ff.f.f.4fffffff...ff.fffff5bbfff.ffffffffff.bb.fbbbb.fffbbbbbbbbbbbbbbbbbbbbbbbb.ff..ffff...fffffbb4f.f..fff.f...f..f...ff...fff..fff.f.b...
fbfbff.f...ffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffbbffafffafffffafaffbbffaf3f..fffff...ff.f.fffffffffff.ffff..bf..
fb.bf.ff..f.ff..ff..ffffffffffffffffff.f.fbbf.5..f.fff.fffbbbbbbfff.fffffbbbbbbbbbbbbbfffbbbfbbbffff.fff.ff..f.ffbbff.ffaff..fffff....ffff..ff.f.f..ffff.f..bf..
fb.fb.fffff.f...f...fffffcff.ff..ff..fffbbfffffffffffffbbbbbbfffffffffbbbbbbbbbbbbffbfbbbffbb...ffffff.ffff...ffbfffff.fff6ff..fff....ffffffffffff...fffff..b.f.
fb.fbf.f..ff.f..f...ffff.ff4fff55ff55bbbffff55555f5ffbbb5fbbffffbbbbbbbbbbbbbbbbbfbbbbffbbbff555ffffff5ffff555bbfffff5f4ffffffffffffffffff..ff...ffff.ffff..b.f.
fbf.b.ff.ff..f.f.f.fff.fff54fff.fffbbf.fffffffffffff.ffffbbbbbbbbbfffbbbbbbbbbfbfbbbbbbbfffff..ffff.ff.fffffbbff.fffffffffff...ffff.f.fff.fffffffff...ff..f.b..f
fbf.fb.f.ff..f.f.fffff.fff5ffff.fbbf..fffffff.5fffbbbbbbb.ffbbbfffbbbbbbbbbfbfbbbffbbbfbbfffff.fff.ffff.ffbb.f.f.fffff.4ffff...fff.f.f.f.fff.f....ff.ffff.ffb..f
fbfffb.f.ff...ff.fffffffff5ff.fbbff.ffffffbbbbbbbbfffbbffbbbffbbbbbbb.bbbfbbbbbffbbbff.ffbb.ffffff.ffff.bbffff..ff.fff.4affff..fff.f.f..f..f.fffffffff.ff.ffb..f
.b.ffb.ff.f...fff.f.ffffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.bbbffbbbbffbff.ffbf..fffff..ffbb.ffff....ffff.f4afff.fff.ffff....ff.ff.....ffff..f.fb...
fbf.f.bff.f...fff.f.ffff.cbbbbbbbbbfb.ffffffff5ff.bbbbbbbbbbbbbfbbbbbbbbbff.bb.fffbffff.fbf..f.fff.fbbff.ff.ff..ff.ff.f4affff.ff.ffff....ff..ff....f..f...ffb...
fbf.f.bff.f...f.fff.f.ffbbbbf.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.fffbff..ffffbbbff.fff.f.ff.f.ff.f4afff.fff.ff.f....ff..f.f.fff..ff..ffbf..
fbf..ffbf..f.ff..ff.fffffcfffff...fb.fffffffff5bb.fbbbbbbfffbbbbfbbbfbbbbbbbfffffbffb.fffbfff.fffbbbf.ff.ff.f.f.ffff...fafff.f.ffff.f...f..fff.ff..f..f.f..fbf..
fbf..ffb...f.f..ff.fffff.fff.ff.ffbb.f.ffffffbb.bbbbbbffffbbbbbbbbbbb.b..b.bf.fffbffbffffbfffffbbbff.fff.ff.ff...fff...faffff..ffff.f..f.....ff..f.f.f..f..fbf..
fb.f.f.fb...fffffffffffffff4ff5bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbff..bff.bbbfffff..ffff.ff...ffffffffffffffffffffffff..ffff..f.f.f...f.fbfff
fb..ff.fb...ff..ff.ffffffffffffbfbff.fffffbbf.5ff.fffffbbbbbbbbfffff.fb...fffff.bfffffffb.fbbb.fffffff.fffffffffffffffffffff.fff.f.fffffffff.f.ff.ff.f....ffbf..
fb..ffff.b..f.ff.f.ff.fffffffffbfbfffffffbaff.5ffffffbbbbbbbfbff.ffffb.ffffffffbfffffff.bbbbf..fffffffffff.fffffffffffffffffffffffffffff.ffffffffffffffffff.bf..
fb..ffff.b.ff..ffffffffffffffffbbffffffbbfffff5ff..bbbbbbbfbb.ff.ffbbffffffffffbfffffffbbbfffffffffff.ffff.ffffff.ffff.ffffffffffffff.......fffff..fffffffffbfff
fbf.f.ff..bff..f.ffffffffff4ff5b...ffbbff3aff.fffbbbbfbbbfbfffffffbfffffffffffbffffffbbbbffffffffff.fffffffffffff.ff...ffffff.ffff.ff.......f..f.ff.f......fbf..
.bff..fff..bf..ffff.ffffffff.f5b..ffbff..fffffbbbbffbbfbbbfffffffbfffffffffffbffffffbbb.bffffff.ff.fff.f.fffff.f.fffffffffffff.f.ffff.......f...f..ff.......bf..
.bfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf.bbfff.fff..ffbfffffbbbfffb.fffffffffffffffff.ff.f.f.ffff4f5fff.f..fffff......f....f.ffff.....bf..
fbfbff.f..ffbf.f.ffff.ffffff.f5bfb.ffffffbbfbbf.fbbb.bb.bf..bfbffffff..f..f.b.ffbbbff.fbffffffffffffffffff.ffff.ffffff.4f5fff.f..f.ff.ff....f.....f.ff.f....bf..
.bfb.ffff..ffbff.f.f.ff6ffffffbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbf.ffb.fbbbff.fffbfffffffffffffffffffffffffffff..4ff6.f.f...fff...f..f......ffff..f...bff.
.bfbf.ffffffffbfffffffffffffffbb..ffffbbbbbffbbffbfbbbffbf.bbfffffffffbfffbfbbbbfffffffbf.fffff.fffffffffffffffffffffff4ff63f.f...ffff...f.f.....f..ff...ff.bff.
.bfbff.fff.ffffbffffffff.ff4bbbbbbbbbbffbffbbfffb.bfbfffbfb.bfff.fffffbffbbbbbfffffffffb....ffffffffffffffffffffffff.fffff6.ff.....f.f....ff.....f..ff.....fbfff
.b.b.fffff.ff..fbffffffffffbbbbbffffffbbfbb.fffbbbffb.ffbb.fbfff.ffff.bfbbbbfffffffffffb......f.ffffffffff.fff.f.fff...4ffffff.....f.f....f.f...f...ff.....fbf.f
.b.b..fffffff..ffbb.fff6fff4..bb.ffffbfbbff.ffbbbfffb.fbbf.fb.ff.fffffbbbb.ff..fffffff.bf.....ffffffffffff.fffff.fff...4f5f.ff....ffff....f..f.f....fff...f.bf.f
.b.b..ff..fffffffffb.ff6fff4..bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.ffff.f.ffffffb.f.....ffffffffffff.ffff..fff...ff56ffff.fffffffffffffffff...fff..f..bff.
.b.b.f.ff.fff..fffffbffffffffffb.bbbb..f.3f.ffbff.fbbbffbfffbfffff.bbbfffff..ffffffffb..ff...ffffffffffffffffff..fff..fff56.ffff.f.f.fff.f....ff.fffff.ff...bfff
.b.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.fffbbbb..ff.ffffffffffbfffffffffff.fffffffffffffff.fff..fff5fff.f.ff.f.f..ff...f..f...ffff....bf.f
fb.ff..f..fffffff.f..ffbbfff.fbbbff.fffff3f...bffbfb..ffb.f.fffbbbbf.ffff.f.fffffffbffffffffffff.fffffffff.fffffffff.ff4ff6ff..fff.f.f..f.ffffffffffff.ff...bf..
fb.ff..ff..ff..ff.f..fff.bbfbbbbbbbbbbbbbbbbbbbbbbbbbbbbbffffbbbbffffff..fff.fffffbffffff.ffffffff.f.ffffffffff.fff.f.fff56ff..ff.ff.f.f....f....f..ff..fff.bf..
fb.ff..ff.f.ff..ffff.ff6fcfbb....ff.ffffffa...bfffb.fffffffbbbbfffffffffffffffff.bfff...fffff.ff.f.ffffffffffff.ffffff.4f5fff.f..fff.f.f...f......f.ff..f..fbf..
.bfff..fff..fffff..ffffffcbffbbb.ffffff..3fff.ff.fbf..ff.bbbbfffffff.ffffff..fffbfff...ffffffff.ffff.ff.ffffffff.ffff..4f5f.ff...ffffff...f........fff..f.f.bf..
.bfff...f...f.f.fff.ffffffffff..bbbfff...3a..fffffbfffbbbbbbff.fff.fff.ffffffffbfffffffffffff.f.ffff.ffff.ffffffffff.f.4ff6.f....ffffff..f.........ff...f.f.b.ff
.bff.f.ff...f.ffff.ffffffffffffffffbbbbbbbbbbbbbbbbbbbbbbbffff..ff.f.fff.ffff.b.ffff...fff.ffffffffffffffffffff.ffff.f.fff6f....f..f.f..f...........f...ff..b...
fbf.fff.f...f..ff.f..f.f.cfffff..f.fff..ffa...fffbfffbbbfffffffffffffffffffffbfff.ff..f.f.f..ff.ffff.ffffffff.fffffffff4ffff..ff...fffff............f..ff..fb...
fbfffff.ff...f..f.f..f.f.fff..fffffffffffffffffffbfbbbfff..ffff..ffffff..f.f.b..fffffffffff...f.ffff.ff.ffffffff.f...ffff56f.f.....ffff............ffff.f..fb.ff
fb.fff...f...f..ff.f..f6ff5ff..ffff..f...3a..f...bbb.f.fff.f.ff..ffffffff..fb.fff.ff.f.fffff..ffffffffff.ffffffffffffffffffff......fff.f...........fff..f..fbf..
fbffff...f...f..f.ff..ffff5ff...fff...f..3a.ff..bbff..ff.fff.ff..fff.f.ff.fb..f.ffff.f.fff..ffffff.fffffffffffffffff.ffffff.......ff.f.f..........fff.f.f.ffb...
.bf.fff..f...f..f..ff.ffff5f.f...fff..fff3ffffbbb..ff..fff..ffff.ff.fff..fbf.f....ffff.ff..ffffffffffffffffffffff....f.fa5ff.....ff..f.f.........ff.f.f.ffffb...
.b.f.ff..ff...f.f...ffffff5f.f...ff.fffffffffbb.b...f.fffff..ffffff.f..ffbffff....fff.ffffffffffffffff..fffffff.ff...ff4a5f.fff.fff.fff.f.....ffff..f..fff.fb...
.b.ffff...f...f.f....fffff54f.f.fff..fff.3fbbfffbfffff..ff.f.f.ffffff...bf.fff....fffffff.ff.ff.ffff.fff.fffffff..fffff4af6....fffffffffffffff..f...fffff.f.b...
.b.f.fff..f...f.f.....f6ffffffffffffff.ffbbaafaaabaaafffafffafaffffafffbfffffffffffffaffffaaaffaffffaffffffffffffaaffffaaf6..ff...f.fff.f......f..fff..ff.f.b...
fbf...fff.ff...ff......fff5ff..fff..f...b3ffff...b....f.fffffffffffff.bffff.ff..fffff.fff....ff.fffffffffffffffffff..f.fffffff...f.f.ff.f.....ffff..f..ff.f.b...
fbf....fffff...fff.....6fff4ff4ffff44f4ff4444ffffbffffffffffffffffffbbf4f444f4ff44f4ffffffffffffffffff44ff4f4ff4fff44f44ffffffffffffffffffffff.....f..ffff..b...
fbf....ffffff..f.f.....6.ff..fffffff.ff..f...f....b.f...f.f.ffff.fbbff.ff...f...fff.fff.f...f.f.ff.ff..fff.f.ff.ff.f.ffff56f.....f.ff.f.f..f.......f.f.fff..b...
fb......fffff...ff.....6.fffffff.ff.ff.f.f...f....bf....f.ff.ffbbb.fffff....f....f.ffff.f...fffffffffffffff.ffff..ffff.fcff......ff.f.f.fff........ff.f..f..b...
fbf.....ffffff..ff.....6.f5ffff.ffff..fff3f..f...fb.....ff.ffbbffffff..ff...f....f.ff.ffff.ff.fffffff.ff.ffffffffffffffff56.....f.f.f.fff..........f..f.ff..b...
.bf.....f.ffffff.ff....6.f5f.fffffff....fff..f.ff..b..ff..fbb.fffff.ff.f.ffff...f..ffffff.fffffffffffffffffffff....fffffcffffffffffffff.f.........ff.f..ff..b...
.bf......f.ff.f.ffffffffffffffffffffff...3fffff....bff..bbbffffff..fff.f....fff.f.ffffffff.ff.ffff.f.ff.ff..ffff...ffff.c56.....ff..f.f.f.......ff.f.f..ff..b...
.bff.....f..ff.f..ff...6.cfcffcffffffffffffffffffffbffbbfffffffffccccfffcccccfcfffffffffffffffcffffcffcffffffffffffffcffc56....ff..f..f.f......f...ff..f.f..b...
.bff.....f..ffff..fffff6..5fff5f5ffff5f5ffffffffffffbbffff5f55ff55555f5fff555f5fff55ffffffff5f5ff5ffffff5f5f5f5ffffff55fff6....f...f..f.f....ff...ff...f.f..b...
.b.ff.....f..ffff..f...fffffffffffffffff.3...ff....fffff...f...fff....ff.fffffffffffffffff.ff.f.fff.fff.ffff.ffffffff..f..ff...f...f..f.f.fff.....f...f..f..b...
.b.fff....f..f.f.f.ff..66666ff66ff66fffffffffffffff66f66666f66fff6fff6fff66ffffff666ffffffff66f6ff6fffff6fffff6f6ff66ffff66.fff....f..ffff.......ff...f..f..b...
fb..fff....f.f..f.ffff......ff...f...ff..3ffff3f3ffff333333f33fff3333fffffffffffffffffffffff3f3ff3f3fffffff33f3ffff333f3fffffffffffffff.f.......f.f..f...f..b...
fb..ff.f...f..f..ff.ff.......ff..f....ff...ffffffffff......f.f.f.f.....ffff..f.ff..fffffffffffffffffff..fff..f.fff.f..f.f...ff..fff..f.f.......f.f...f...f..b...
fb...fff...f..f...ff.fff.....ff..ff...ff.....fffffffffffffffffffffffffff.ffff..ff.ff.fff..ff..ffff.f....ff...f.f.f..ff.ff..f.f....ffff.f.....ff..f..f....f..b...
fb....f.f...f..f...ffffffff..f.f.ff....ff...fffff.f....fff.f..f...f....f...ff..fff...fffff.ffffff.ff...f.f...ffff.....fff.f..f...f...fffff.ff....f..f....f..b..f
fb....ff.f..f..f....fff.f..fffffffffffffffff..f..fff......fff.f....f...f..f..ffffffffffff.ffff.fff.f..f.ff..ffff........fff.f....f..f.f.ffffffffffffffffffffbff.
fbf....f..ff.f.f......fff....f.f.ff.f....ff.fffff...ffffff.f.ffff...f..f.ffff.fff....ffffffff.fff..f.f.ff...ffff.......ff..fffffffffffff........f.f......f..b...
fbf.....f...ff..f......fff...f..f.fff....f.f..f..f...fffffffffffffffffffffffffffffffffffff.f.ffff..f.f.ff.fff.ff......f.f..f....f..f.f..........f.f......f..b...
fbf......f...f..f.......ffff.f..f.f..ff...fff.f..f..ff.f..f.f........ffff.......fffffffff.f.fffff..ff.f.ff.fff.f....ff..f..f....f.f.f...........ff.......f..b...
.bff.....f....f..f.......fffff...f.f..ffffffffffffff....fff.f.........ff........f..ffff.fffff.f.ff.f.f.ff.ff...f..ff....f.f....f..f.f...........f........f..b...
fbff......f...ffff.......f.fff...f.f..f....f.fff.f........ff.........f.ff.......f.ffffffffff..f.f.ff.ff.ffff...fff......ff.....f.f.f...........ff........f..b...
.b.ff.....ff...f.ff.......f.fffff.ff...f...f..ffff.......f.fff.....ff..f.ff.....ffff..fffff.f.f.ff.ff..fff.fffff........ff....f.f.f............f.........f..b...
.bfff......ff..f..f........f.ff.fff.f...f...fffffff......ff...ff..f.....f..ff.fff..ffffff..fffffffffffffffff...f........f.....ff.f............ff........f...b...
.bff.f......ff..f..ff.......ffff.fffff...f......ff.ff....f.....ffff.....f..fffff.fff.fff....fffff.ffffff..f....f.......ff....ff.f............ff.........f...b...
.bf.ff......f.fff..f.ff......f.fff.fffffff......f.ffffffff...ff....ffff.fff..fffffffff..f.ffffffffff.fff.f.....f.......ff....f.f.............ff.........f...b...
.bf..ff......f..ff..f..ff.....f.f.ffffffffffff..f....ffffffff......fffffffffffffffffffffffffffffff.ff.f.ff....f.......ff...ffff.............ff.........f....b...
.b.f.fff......f..f..f....ff...ff.ff.fff..fffffffffffffffffffffffffffffffffffff.ffff.....f...ff.ff.ff..f.fff...f.......f...fff..............f.f.........f....b..f
.b.f..fff.....f...ff.f.....ff.f.f..f.ffff...f....f....f...fffffffffffffffff.fffff..f.....ffff.f.ffffff.f...ff.f......ff.ffff..............f..f.........f....b..f
.b.f..f.ff.....f..f.ff.......fff.f..ffff.fff.f....f..ff.................ffffff..f..f.....f.fff.fff.fffff.....ff.....fffffff..............f..f.........f.....b.f.
.b.f...f.ff.....f..f.ff........fffff..fff...ffff..f.ff...............fffffff...f....f...f.fffff...f.fffffffffffffffffff..f..............f...f.........f.....b.ff
.b..f...ff.ff...f..f..fff......f..ffff.fff.....ffffffffffffffffffffffffff..f...f.....fff..fff......ffff......f...fff.....f.............f...f.........f......bff.
.b..f....ff..f...f..f..f.ff.....f....fffffff....ff.f.............ffff......f..f......ff.ffff........f..fffffffffffffff..f............ff....f.........f...fffbf..
.b...f....ff..ff..f.f..f...fff..f......ff.ffffffffffffffffffffffff..........f.f....ff..ff.ff.......fff......f....f....fff...........f......f........f.fff...bf..
.b...f.....ff...ff.f.f..f.....ffff......ff.f.fffff.ff.......fff.............ff...ff.fff.fff.f......f.ff....f...ff.....f..ffff......f......f.......ffff......b...
.b...f......ff....fff.f..f.......ffff....ffff..fffffff..ffff................ff.ffffff....ffff.....f..f.ff..f.fff......f......fffffffffffffffffffff.f.......fb...
fb....f......fff....fff..f........f..fffffffffffffffffff....................fffffff.....ff..ff..fff...f..ffff.f......f..........f........f.........f.......fb...
.b....f.......f.f....fffffffffffffffffff...ff..fff....ffffffffffffffffffffffffff........ff....fffffffffffff..f......f.........ff.........f........f.......f.b...
.bf...f........f.fff..ffffff.......f.....fff....f.fffff..f..............fffff..f.......ff.....ff.f.....f.f.ff......f.........f..........f........f........f.b..f
.b.f...f........f...fffff..fff.....f..fff...f....ff...ffffffffffffffffffff......f......ff...ff.ff......f.f.f.f....f........ff...........f.......f........f..b..f
.b..f..f.........f.....fffffffffffffff.......f.....f....f...ff....fff....f......f.....ff...f...ff.......f.f...ff.f.......ff............f........f.......f...b.f.
.b...f..f.........f......f...f...fffff........f.....ff..f....fffff......f........f....f..ff....f.f.....fff......ff.....ff..............f.......f........f...bf..
.bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb...
.......ff...........f......f..f.......f........f........fff.......fff.f............ffff......f.....f..ff..f...f...fffff..............f.......f........f....f....
.........f...........ff....ff..f.......f........f..........ffff......fff........ffffff.......f......ff....f.ff.fff.....ff............f......f........f...ff...ff
.........ff............f....ff..f.......f........f..........f..fffffffffffffffff...ffff.....f.......f.f....ffff..........ffff.......f.....ff........f...f.ffff..
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
